# ID
STUDIO_ID = "S01"
SESSION_ID = "SESSION_001"

# FPS control
PROCESS_EVERY_N_FRAMES = 2

# Smoothing
SMOOTH_WINDOW = 15

# Threshold Head Pose
PITCH_DOWN_START = 15
PITCH_DOWN_STRICT = 20

# NOT FACING
YAW_THRESHOLD = 15

# Time-based rule
HEAD_DOWN_MIN_SECONDS = 1.5
OFF_FRAME_MIN_SECONDS = 1
NOT_FACING_MIN_SECONDS = 0.8

# State cooldown
STATE_HOLD_SECONDS = 1

# Camera
CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480