# ID
STUDIO_ID = "S01"
SESSION_ID = "SESSION_001"

# FPS control
PROCESS_EVERY_N_FRAMES = 2

# Smoothing
SMOOTH_WINDOW = 15

# Threshold Head Pose
PITCH_DOWN_START = 10
PITCH_DOWN_STRICT = 10

# NOT FACING
YAW_THRESHOLD = 15

# Time-based rule
HEAD_DOWN_MIN_SECONDS = 1
OFF_FRAME_MIN_SECONDS = 1
NOT_FACING_MIN_SECONDS = 1

# State cooldown
STATE_HOLD_SECONDS = 1

# Camera
CAMERA_INDEX = 1